# Generated by Django 4.0.4 on 2022-05-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
